databases:
  - name: goki_net
    databaseName: goki_net
    user: root
    region: singapore

services:
  - type: web
    name: goki-net
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: goki_net
          property: connectionString
      - key: <%= E.V['RAILS_MASTER_KEY'] %>
        sync: false
services:
  - type: cron
    name: gokinet-cron
    env: ruby
    plan: starter
    region: singapore
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec rake fight_status:change_to_be_done
    schedule: 0 0 * * *
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: goki_net
          property: connectionString
      - key: <%= E.V['RAILS_MASTER_KEY'] %>
        sync: false
